### ISSUE TITLE
Reflect PWT to users page

### ISSUE THREAD

**Issue by yangroro** [ridi/intranet#126]
PWT도 직원찾기 메뉴에 반영되면 좋을 것 같습니다.

**Comment by imkitae** [comment]
PWT가 사라진 관계로(...) close하겠습니다.

**Comment by yangroro** [comment]
@imkitae 10층에는 아직 남아있지 않나요? 그래서 close 하지 않았는데...

**Comment by imkitae** [comment]
@yangroro 앗 그렇군요 11층만 적용이었죠 제가 착각했네요!

**Comment by freekering** [comment]
10층도 PWT가 사라졌으므로 다시 close하겠습니다.
