### ISSUE TITLE
Move service variables in .env to DB

### ISSUE THREAD

**Issue by imkitae** [ridi/intranet#30]
자주 변경되고 서비스에 밀접한 변수들은 .env가 아니라 db에서 관리되어야 한다고 생각합니다.
매번 서버에 접속해서 수정하는데 실수할 여지도 높고 불편합니다.

**Comment by namenu** [comment]
이거는 작업이 진행되지 않았나요?

**Comment by imkitae** [comment]
대부분 DB로 옮겨졌지만 url 정보가 남았습니다.
