### ISSUE TITLE
인트라넷 직원찾기 타일에 커서 이동시 폰트 흔들림현상

### ISSUE THREAD

**Issue by JungleKim** [ridi/intranet#45]
타일왔다갔다할시 타일에적힌 이름이 흔들리는 현상이있습니다.ㅠㅠ

**Comment by jaeminbae** [comment]
아래 커밋으로 해결 완료하였습니다.
https://github.com/ridi/intranet/commit/5ca10009a22a2cd9970e85e1de1e42e97974c8c3
