### ISSUE TITLE
직원 프로필 클릭시 403 Forbidden

### ISSUE THREAD

**Issue by namenu** [ridi/intranet#46]

**Comment by imkitae** [comment]
페이지에 접근할 때마다 S3에 접근할 수 있는 pre-signed  url을 생성해서 이미지에 접근합니다. 이 때 설정한 expire time이 현재 3분이기 때문에 페이지를 열고 나서 3분 뒤에 사진을 보려고 하면 요청이 거부되고 있습니다. (새로고침하면 보임)

사진 정보는 보안에 민감한 정보는 아니므로 공개로 열어두어도 될 것 같습니다.
